name: FB monitor bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: DEBUG repo contents
        run: |
          echo "PWD:"
          pwd
          echo "FILES:"
          ls -la
          echo "BOT.PY CONTENT:"
          cat bot.py

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        env:
          PYTHONUNBUFFERED: "1"
        run: python bot.py
